import type { Exam, Paper, Question } from '@shared/schema';

export const mockExams: Exam[] = [
  {
    id: 1,
    name: 'JEE Main',
    description: 'Joint Entrance Examination for engineering admissions',
    icon: 'calculator',
    category: 'Engineering',
    isPopular: true,
    totalQuestions: 12450,
    yearsAvailable: 20,
    createdAt: new Date(),
  },
  {
    id: 2,
    name: 'NEET UG',
    description: 'National Eligibility cum Entrance Test for medical',
    icon: 'heartbeat',
    category: 'Medical',
    isPopular: true,
    totalQuestions: 8200,
    yearsAvailable: 15,
    createdAt: new Date(),
  },
  {
    id: 3,
    name: 'GATE',
    description: 'Graduate Aptitude Test in Engineering',
    icon: 'cogs',
    category: 'Engineering',
    isPopular: false,
    totalQuestions: 15600,
    yearsAvailable: 25,
    createdAt: new Date(),
  },
];

export const mockPapers: Paper[] = [
  {
    id: 1,
    examId: 1,
    year: 2023,
    title: 'JEE Main 2023 Session 1',
    totalQuestions: 90,
    duration: 180,
    isFree: true,
    createdAt: new Date(),
  },
  {
    id: 2,
    examId: 1,
    year: 2022,
    title: 'JEE Main 2022 Session 1',
    totalQuestions: 90,
    duration: 180,
    isFree: true,
    createdAt: new Date(),
  },
  {
    id: 3,
    examId: 1,
    year: 2021,
    title: 'JEE Main 2021 Session 1',
    totalQuestions: 90,
    duration: 180,
    isFree: false,
    createdAt: new Date(),
  },
];

export const mockQuestions: Question[] = [
  {
    id: 1,
    paperId: 1,
    questionNumber: 1,
    questionText: 'What is the derivative of sin(x)?',
    options: ['cos(x)', '-cos(x)', 'sin(x)', '-sin(x)'],
    correctAnswer: 'cos(x)',
    explanation: 'The derivative of sin(x) with respect to x is cos(x). This is a fundamental result in calculus.',
    subject: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'Easy',
    createdAt: new Date(),
  },
  {
    id: 2,
    paperId: 1,
    questionNumber: 2,
    questionText: 'Which of the following is the correct formula for kinetic energy?',
    options: ['KE = ½mv²', 'KE = mv²', 'KE = 2mv²', 'KE = m²v'],
    correctAnswer: 'KE = ½mv²',
    explanation: 'Kinetic energy is the energy possessed by an object due to its motion. The formula is KE = ½mv², where m is mass and v is velocity.',
    subject: 'Physics',
    topic: 'Mechanics',
    difficulty: 'Easy',
    createdAt: new Date(),
  },
];
